# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Attribute-Persistent
version:      1.1
version_from: Persistent.pm
installdirs:  site
requires:
    AnyDBM_File:                   0
    Attribute::Handlers::Prospective: 0
    Digest::MD5:                   0
    MLDBM:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
